version: '3.5'

services:
  tp-express:
    container_name: express
    build: 
      context: back/express
    restart: always
    networks:
      - app
    ports:
      - '127.0.0.1:${EXPRESS_PORT}:${EXPRESS_PORT}'
    volumes:
      - './docker-data/express/security/RSA:/usr/src/app/security/RSA'
    environment:
      - 'EXPRESS_PORT=${EXPRESS_PORT}'
      - 'BASE_URL=${BASE_URL}'
      - 'IPFS_PORT=${IPFS_PORT}'
      - 'IPFS_PROTOCOL=${IPFS_PROTOCOL}'
      - 'LOTUS_PORT=${LOTUS_PORT}'
      - 'LOTUS_PROTOCOL=${LOTUS_PROTOCOL}'
      - 'LOTUS_AUTH_TOKEN=${LOTUS_AUTH_TOKEN}'
  tp-ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    networks:
      - app
    restart: always
    ports:
      - "${IPFS_PORT}:${IPFS_PORT}" # ipfs swarm - expose if needed/wanted
      - "${SWARM_PORT}:${SWARM_PORT}" # ipfs api - expose if needed/wanted
      - "127.0.0.1:${GATE_PORT}:${GATE_PORT}" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./docker-data/ipfs:/ipfsdata
  tp-nginx:
    container_name: nginx
    build: nginx
    ports:
      - '127.0.0.1:33:33'
    restart: always
    networks:
      - app
  tp-next:
    container_name: next
    build:
      context: front/next12
    ports:
      - "127.0.0.1:${NEXT_PORT}:${NEXT_PORT}"
    restart: always
    networks:
      - app
    environment:
      - "EXPRESS_PORT=${EXPRESS_PORT}"
      - "BASE_URL=${BASE_URL}"

networks:
  app:
    driver: bridge
