[profile.default]
auto_detect_solc = true
offline = false
optimizer = true
optimizer_runs = 200
optimizer_details.yul_details = false
src = './contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
gas_reports = ["gasusage"]

[profile.default.optimizer_details]
constantOptimizer = true
yul = false